"""Minimal stub for :mod:`duckduckgo_search` used in tests."""

from __future__ import annotations

from typing import List


class DDGS:  # pragma: no cover - deterministic stub
    def text(self, query: str, max_results: int = 8) -> List[dict]:
        return [
            {
                "title": f"Stub result for {query}",
                "href": "https://example.com/stub",
                "body": f"Autogenerated summary for {query}",
            }
            for _ in range(max(1, max_results))
        ]


__all__ = ["DDGS"]
